//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLTKSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NLTKSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank	   Word	Part of speech	Frequency	Dispersion
        ///1	   the	a	22038615	0.98
        ///2	   be	v	12545825	0.97
        ///3	   and	c	10741073	0.99
        ///4	   of	i	10343885	0.97
        ///5	   a	a	10144200	0.98
        ///6	   in	i	6996437	0.98
        ///7	   to	t	6332195	0.98
        ///8	   have	v	4303955	0.97
        ///9	   to	i	3856916	0.99
        ///10	   it	p	3872477	0.96
        ///11	   I	p	3978265	0.93
        ///12	   that	c	3430996	0.97
        ///13	   for	i	3281454	0.98
        ///14	   you	p	3081151	0.92
        ///15	   he	p	2909254	0.94
        ///16	   with	i	2683014	0.99
        ///17	   on	i	2485306	0.99
        ///18	   do	v	2573587	0.95
        ///19	   sa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _5000words {
            get {
                return ResourceManager.GetString("_5000words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the	9243		(definite article, adverb)
        ///of	5220		(preposition, auxiliary verb)
        ///and	5196		(conjunction)
        ///to	4951		(preposition, adverb)
        ///a	4506		(indefinite article, noun, preposition)
        ///in	2822		(preposition, adverb)
        ///is	2699		(verb)
        ///you	2041		(pronoun, noun)
        ///are	1843		(verb)
        ///for	1752		(preposition, conjunction)
        ///that	1743		(pronoun, adjective, adverb,	conjunction)
        ///or	1487		(conjunction)
        ///it	1386		(pronoun, noun)
        ///as	1363		(adverb, conjunction, pronoun, preposition)
        ///be	1145		(verb, auxiliary verb)
        ///on	10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wordfrequency {
            get {
                return ResourceManager.GetString("wordfrequency", resourceCulture);
            }
        }
    }
}
